project_id = "jpcwzjqzfyzpcwcbekge"

[functions.send-push-notification]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.contract-link]
verify_jwt = false
